version: '3'

services:
  bap_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4021:4021
    networks:
      - samagra_compass

networks:
  samagra_compass:
    external: true

#  postgres:
#    image: postgres:15.3-alpine
#    ports:
#      - ${DATABASE_PORT}:5432
#    volumes:
#      - ./.data/db:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: ${DATABASE_USERNAME}
#      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#      POSTGRES_DB: ${DATABASE_NAME}

